version: '3'

services:

  db:
    build: .docker/postgres
    container_name: crunch-prisma-db
    restart: always
    tty: true
    ports: 
      - "5432:5432"
      - "5555:5555"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prisma